# Generated by Django 4.2.7 on 2025-07-03 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('agent', 'Real Estate Agent'), ('developer', 'Property Developer'), ('manager', 'Property Manager'), ('advisor', 'Investment Advisor')], default='agent', max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('port-harcourt', 'Port Harcourt'), ('ibadan', 'Ibadan'), ('kaduna', 'Kaduna')], max_length=20)),
                ('bio', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('specialties', models.CharField(help_text='Comma-separated specialties', max_length=500)),
                ('languages', models.CharField(help_text='Comma-separated languages', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='agent_profiles/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
