# Generated by Django. Add the account_type field to UserProfile.
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=10),
        ),
    ]
