# Generated by Django 4.2.7 on 2025-07-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('terrace', 'Terrace'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('shortlet', 'Shortlet')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('port-harcourt', 'Port Harcourt'), ('ibadan', 'Ibadan'), ('kaduna', 'Kaduna')], max_length=20)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('square_feet', models.PositiveIntegerField()),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('min_stay_nights', models.PositiveIntegerField(blank=True, help_text='For shortlets only', null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_main', 'created_at'],
            },
        ),
    ]
